# Classification Models

In [1]:
import json
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.metrics import confusion_matrix, recall_score, precision_score, classification_report, accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.externals import joblib

with open('/notebooks/data/x.json', 'r') as file:
    x = json.load(file)

with open('/notebooks/data/y.json', 'r') as file:
    y = json.load(file)
    
vectorizer = TfidfVectorizer()
Xtrain = vectorizer.fit_transform(x).toarray()
Ytrain = np.asarray(y)

## MultinomialNB

In [2]:
modelMultinomialNB = MultinomialNB(alpha=0.01).fit(Xtrain, Ytrain)
joblib.dump(modelMultinomialNB, 'MultinomialNB.pkl')

YmodelMultinomialNBPredict = modelMultinomialNB.predict(Xtrain)

print confusion_matrix(Ytrain, YmodelMultinomialNBPredict, labels=list(set(Ytrain)))
print classification_report(Ytrain, YmodelMultinomialNBPredict)
# print cross_val_score(modelMultinomialNB, Xtrain, Ytrain, cv=10)

[[1157    0  202    0    0   38    5    6   12]
 [   0  200    0    0    0    0    0    0    0]
 [  43    0 1660    0    0    2   11   10    1]
 [   0    0    1  808    0    0    0    0    0]
 [   0    0   27    0  305    0    0    0    0]
 [   2    0   14    0    0   74    0    0    0]
 [   0    0  123    0    0    0   40    0    0]
 [   0    0    4    0    0    2    0  160    0]
 [   0    0    2    0    0    0    0    0   60]]
                precision    recall  f1-score   support

            cv       0.91      0.96      0.94       166
         other       0.82      0.96      0.88      1727
        resume       0.96      0.81      0.88      1420
    transcript       0.71      0.25      0.37       163
ประวัติส่วนตัว       0.82      0.97      0.89        62
          ราคา       1.00      1.00      1.00       200
      สมัครงาน       0.64      0.82      0.72        90
      หลักสูตร       1.00      1.00      1.00       809
          อบรม       1.00      0.92      0.96       332

   av

## GaussianNB

In [ ]:
# modelGaussianNB = GaussianNB().fit(Xtrain, Ytrain)
# joblib.dump(modelGaussianNB, 'GaussianNB.pkl')

# YmodelGaussianNBPredict = modelGaussianNB.predict(Xtrain)

# print confusion_matrix(Ytrain, YmodelGaussianNBPredict, labels=list(set(Ytrain)))
# print classification_report(Ytrain, YmodelGaussianNBPredict)
# print cross_val_score(modelGaussianNB, Xtrain, Ytrain, cv=10)

## BernoulliNB

In [ ]:
# modelBernoulliNB = BernoulliNB(alpha=0.01).fit(Xtrain, Ytrain)
# joblib.dump(modelBernoulliNB, 'BernoulliNB.pkl')

# YmodelBernoulliNBPredict = modelBernoulliNB.predict(Xtrain)

# print confusion_matrix(Ytrain, YmodelBernoulliNBPredict, labels=list(set(Ytrain)))
# print classification_report(Ytrain, YmodelBernoulliNBPredict)
# print cross_val_score(modelBernoulliNB, Xtrain, Ytrain, cv=10)